Repository Team-SilverTown/Team-SilverTown-MasilGasil-FE, pull requests merged in 2024-03, with the labels that each got.

#120 [Refactoring] LogRecord
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.model.tsx
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.model.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.model.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.styles.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.model.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.styles.ts
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/app/log/record/components/index.ts
  src/app/log/record/context/LogRecordContext.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
  src/app/log/record/hooks/useGeoLocationUtils.ts
  src/app/log/record/page.tsx
  src/app/log/record/utils/getTwoPointDistance.ts
  src/components/MasilMap/MasilMap.tsx
  src/components/Textarea/Textarea.styles.ts
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  yarn.lock
Labels: refactor

#130 [Feat] 회원정보 수정 페이지 구현
  src/app/signin/SignIn.controller.tsx
  src/app/signin/sections/SignInStep2.tsx
  src/app/user/[id]/setting/edit/UserEdit.styles.ts
  src/app/user/[id]/setting/edit/UserEdit.types.ts
  src/app/user/[id]/setting/edit/UserEdit.view.tsx
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.tsx
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.tsx
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.tsx
  src/app/user/[id]/setting/edit/components/UserEditInput/UserEditInput.tsx
  src/constants/variable.ts
  src/types/OriginDataType/IntensityOption.ts
  src/types/OriginDataType/SexOption.ts
  src/types/OriginDataType/index.ts
Labels: enhancement

#129 [Feat] UserEdit 닉네임 , 성별 input 구현
  src/app/signin/SignIn.constants.ts
  src/app/signin/SignIn.controller.tsx
  src/app/signin/sections/SignInStep1.tsx
  src/app/signin/sections/SignInStep2.tsx
  src/app/signin/sections/SignInStep3.tsx
  src/app/user/[id]/setting/UserSetting.controller.tsx
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.controller.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.view.tsx
  src/app/user/[id]/setting/edit/UserEdit.constants.ts
  src/app/user/[id]/setting/edit/UserEdit.controller.tsx
  src/app/user/[id]/setting/edit/UserEdit.model.ts
  src/app/user/[id]/setting/edit/UserEdit.styles.ts
  src/app/user/[id]/setting/edit/UserEdit.types.ts
  src/app/user/[id]/setting/edit/UserEdit.view.tsx
  src/app/user/[id]/setting/edit/components/EditBirthDate/EditBirthDate.tsx
  src/app/user/[id]/setting/edit/components/EditBodyInfo/EditBodyInfo.styles.ts
  src/app/user/[id]/setting/edit/components/EditBodyInfo/EditBodyInfo.tsx
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.styles.ts
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.tsx
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.styles.ts
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.tsx
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.styles.ts
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.tsx
  src/app/user/[id]/setting/edit/components/UserEditInput/UserEditInput.styles.ts
  src/app/user/[id]/setting/edit/components/UserEditInput/UserEditInput.tsx
  src/app/user/[id]/setting/edit/components/index.ts
  src/app/user/[id]/setting/edit/page.tsx
  src/components/Button/Button.tsx
  src/components/InputRadio/InputRadio.styles.ts
  src/components/InputRadio/InputRadio.tsx
  src/components/index.ts
  src/constants/userValidate.ts
  src/constants/variable.ts
  src/styles/theme.ts
  src/types/OriginDataType/IntensityOption.ts
  src/types/OriginDataType/SexOption.ts
  src/types/OriginDataType/index.ts
Labels: enhancement

#122 Faeture/user edit layout/#121
  src/app/signin/SignIn.constants.ts
  src/app/signin/SignIn.controller.tsx
  src/app/signin/sections/SignInStep1.tsx
  src/app/signin/sections/SignInStep2.tsx
  src/app/signin/sections/SignInStep3.tsx
  src/app/user/[id]/setting/UserSetting.controller.tsx
  src/app/user/[id]/setting/UserSetting.styles.ts
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/SettingContent/SettingContent.styles.ts
  src/app/user/[id]/setting/components/SettingContent/SettingContent.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.controller.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.view.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.view.tsx
  src/app/user/[id]/setting/edit/UserEdit.constants.ts
  src/app/user/[id]/setting/edit/UserEdit.controller.tsx
  src/app/user/[id]/setting/edit/UserEdit.model.ts
  src/app/user/[id]/setting/edit/UserEdit.styles.ts
  src/app/user/[id]/setting/edit/UserEdit.types.ts
  src/app/user/[id]/setting/edit/UserEdit.view.tsx
  src/app/user/[id]/setting/edit/components/EditBirthDate/EditBirthDate.tsx
  src/app/user/[id]/setting/edit/components/EditBodyInfo/EditBodyInfo.styles.ts
  src/app/user/[id]/setting/edit/components/EditBodyInfo/EditBodyInfo.tsx
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.styles.ts
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.tsx
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.styles.ts
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.tsx
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.styles.ts
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.tsx
  src/app/user/[id]/setting/edit/components/UserEditInput/UserEditInput.styles.ts
  src/app/user/[id]/setting/edit/components/UserEditInput/UserEditInput.tsx
  src/app/user/[id]/setting/edit/components/index.ts
  src/app/user/[id]/setting/edit/page.tsx
  src/components/Button/Button.tsx
  src/components/InputRadio/InputRadio.styles.ts
  src/components/InputRadio/InputRadio.tsx
  src/components/ShadcnUi/ui/switch.tsx
  src/components/index.ts
  src/constants/userValidate.ts
  src/constants/variable.ts
  src/styles/theme.ts
  src/types/OriginDataType/IntensityOption.ts
  src/types/OriginDataType/SexOption.ts
  src/types/OriginDataType/index.ts
  yarn.lock
Labels: enhancement

#139 [Feat] MateDetail 메이트 정보란 구현
  src/app/mate/[id]/MateDetail.styles.ts
  src/app/mate/[id]/MateDetail.tsx
  src/app/mate/[id]/MateDetail.types.ts
  src/app/mate/[id]/components/MateInfo/MateInfo.styles.module.css
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.tsx
  src/app/mate/[id]/components/MateInfo/components/MateToggleMenu/MateToggleMenu.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateToggleMenu/MateToggleMenu.tsx
  src/app/mate/[id]/components/MateInfo/components/index.ts
  src/app/mate/[id]/page.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Divider/Divider.tsx
  src/hooks/useToggle.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: enhancement

#137 [Feat] MateDetail 참가자, 유저 평가 구역 구현
  src/app/mate/[id]/MateDetail.styles.ts
  src/app/mate/[id]/MateDetail.tsx
  src/app/mate/[id]/MateDetail.types.ts
  src/app/mate/[id]/components/MateEvaluation/MateEvaluation.styles.ts
  src/app/mate/[id]/components/MateEvaluation/MateEvaluation.tsx
  src/app/mate/[id]/components/MateInfo/MateInfo.styles.module.css
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.tsx
  src/app/mate/[id]/components/MateInfo/components/MateToggleMenu/MateToggleMenu.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateToggleMenu/MateToggleMenu.tsx
  src/app/mate/[id]/components/MateInfo/components/index.ts
  src/app/mate/[id]/components/MateMembers/MateMembers.tsx
  src/app/mate/[id]/page.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Divider/Divider.tsx
  src/hooks/useToggle.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  tailwind.config.ts
Labels: enhancement

#135 [Feat] Mate Detail 페이지 레이아웃 구현
  src/app/layout.tsx
  src/app/mate/[id]/MateDetail.styles.ts
  src/app/mate/[id]/MateDetail.tsx
  src/app/mate/[id]/MateDetail.types.ts
  src/app/mate/[id]/components/MateEvaluation/MateEvaluation.styles.ts
  src/app/mate/[id]/components/MateEvaluation/MateEvaluation.tsx
  src/app/mate/[id]/components/MateInfo/MateInfo.styles.module.css
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.tsx
  src/app/mate/[id]/components/MateInfo/components/MateToggleMenu/MateToggleMenu.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateToggleMenu/MateToggleMenu.tsx
  src/app/mate/[id]/components/MateInfo/components/index.ts
  src/app/mate/[id]/components/MateMembers/MateMembers.tsx
  src/app/mate/[id]/components/index.ts
  src/app/mate/[id]/page.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Divider/Divider.tsx
  src/hooks/useToggle.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  tailwind.config.ts
Labels: enhancement

#142 [Feat] LogRecord SETP3 BottomSheet 구현
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.model.tsx
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.model.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.model.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.styles.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.model.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.styles.ts
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/app/log/record/components/index.ts
  src/app/log/record/context/LogRecordContext.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
  src/app/log/record/page.tsx
  src/app/log/record/utils/getTwoPointDistance.ts
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/store/useMasilMapStore.ts
  src/components/Textarea/Textarea.styles.ts
  src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.styles.ts
  src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.tsx
  src/components/modalViews/LogRecordDoneModal/animationData.json
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/hooks/useGeoLocationUtils.ts
  yarn.lock
Labels: enhancement

#115 [Feat] Search Top Navigator 레이아웃 구현
  src/app/explore/Explore.controller.tsx
  src/app/explore/Explore.model.tsx
  src/app/explore/components/SearchBar/SearchBar.styles.ts
  src/app/explore/components/SearchBar/SearchBar.tsx
  src/app/explore/components/TabItem/TabItem.styles.ts
  src/app/explore/components/TabItem/TabItem.tsx
  src/app/explore/components/index.ts
  src/app/explore/sections/BottomSheetSection.tsx
  src/app/explore/sections/BottomSheetSection/BottomSheetSection.styles.ts
  src/app/explore/sections/BottomSheetSection/BottomSheetSection.tsx
  src/app/explore/sections/MapSection.tsx
  src/app/explore/sections/MapSection/MapSection.styles.ts
  src/app/explore/sections/MapSection/MapSection.tsx
  src/app/explore/sections/index.ts
  src/app/layout.tsx
  src/components/BottomSheet/SheetContent.tsx
  src/components/BottomSheet/SheetHeader.tsx
  src/components/BottomSheet/sheet.tsx
  src/components/BottomSheet/styles.ts
  src/components/BottomSheet/use-prevent-scroll.ts
  src/components/Button/Button.tsx
  src/components/OrderTab/OrderTab.styles.ts
  src/components/OrderTab/OrderTab.tsx
  src/components/OrderTab/index.ts
  src/components/Tab/Tab.styles.ts
  src/components/Tab/Tab.tsx
  src/components/index.ts
  src/components/navigators/TopNavigator/TopNavigator.tsx
Labels: enhancement, refactor

#150 [Refactor] API 핸들러 CRUD 메소드 추가
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.tsx
  src/lib/api/clientRootAPI.ts
  src/lib/api/serverRootAPI.ts
Labels: refactor

#158 [Refactoring] 회원가입 + 유저 정보 수정 페이지 공통 컴포넌트 작업
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.styles.ts
  src/app/signin/sections/SignInStep1.tsx
  src/app/signin/sections/SignInStep2.tsx
  src/app/signin/sections/SignInStep3.tsx
  src/app/signin/sections/SignInStep4.tsx
  src/app/user/[id]/setting/edit/UserEdit.constants.ts
  src/app/user/[id]/setting/edit/components/EditBirthDate/EditBirthDate.tsx
  src/app/user/[id]/setting/edit/components/EditBodyInfo/EditBodyInfo.tsx
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.styles.ts
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.tsx
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.tsx
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.tsx
  src/app/user/[id]/setting/edit/components/UserEditInput/UserEditInput.styles.ts
  src/app/user/[id]/setting/edit/components/index.ts
  src/components/UserEditInput/UserEditInput.styles.ts
  src/components/UserEditInput/UserEditInput.tsx
  src/components/UserIntensityItem/UserIntensityItem.styles.ts
  src/components/UserIntensityItem/UserIntensityItem.tsx
  src/components/index.ts
  src/lib/constants/userConstants.ts
  src/lib/constants/variable.ts
  yarn.lock
Labels: enhancement, refactor

#166 [Refact] auth refactoring
  d.types/next-auth.d.ts
  next.config.mjs
  package.json
  src/app/Main.controller.tsx
  src/app/Main.model.tsx
  src/app/Main.view.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/auth/kakao/page.tsx
  src/app/layout.tsx
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.model.tsx
  src/app/signin/components/StepButton/StepButton.tsx
  src/app/signin/sections/SignInStep1.tsx
  src/app/signin/sections/SignInStep2.tsx
  src/app/signin/sections/SignInStep4.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/components/navigators/navInablePath.ts
  src/lib/AuthContext.tsx
  src/lib/AuthLoader.tsx
  src/lib/api/User/client.ts
  src/lib/api/User/server.ts
  src/lib/api/axios/axiosConfig.ts
  src/lib/api/clientRootAPI.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/lib/api/serverRootAPI.ts
  src/lib/constants/userConstants.ts
  src/lib/constants/variable.ts
  src/lib/hooks/useEventQuery.ts
  src/stores/useAuthStore.ts
  src/stores/useMeStore.ts
  src/types/OriginDataType/SexOption.ts
  src/types/Request/User.ts
  src/types/Response/User.ts
  src/types/Response/index.ts
  yarn.lock
Labels: enhancement

#161 [Feat] PostCreate Step1 구현
  next.config.mjs
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/post/create/PostCreate.constants.ts
  src/app/post/create/PostCreate.controller.tsx
  src/app/post/create/PostCreate.styles.ts
  src/app/post/create/PostCreate.types.ts
  src/app/post/create/PostCreate.view.tsx
  src/app/post/create/components/PostPinEdit/PostPinEdit.controller.ts
  src/app/post/create/components/PostPinEdit/PostPinEdit.styles.ts
  src/app/post/create/components/PostPinEdit/PostPinEdit.view.tsx
  src/app/post/create/components/PostTextEdit/PostTextEdit.controller.ts
  src/app/post/create/components/PostTextEdit/PostTextEdit.styles.ts
  src/app/post/create/components/PostTextEdit/PostTextEdit.view.tsx
  src/app/post/create/components/PostTextEdit/components/PostContentEdit/PostContentEdit.tsx
  src/app/post/create/components/PostTextEdit/components/PostPublicEdit/PostPublicEdit.styles.ts
  src/app/post/create/components/PostTextEdit/components/PostPublicEdit/PostPublicEdit.tsx
  src/app/post/create/components/PostTextEdit/components/PostThumbnailEdit/PostThumbnailEdit.styles.ts
  src/app/post/create/components/PostTextEdit/components/PostThumbnailEdit/PostThumbnailEdit.tsx
  src/app/post/create/components/PostTextEdit/components/PostTitleEdit/PostTitleEdit.tsx
  src/app/post/create/components/PostTextEdit/components/index.ts
  src/app/post/create/context/PostCreateContext.tsx
  src/app/post/create/context/reducer/PostCreateReducer.ts
  src/app/post/create/page.tsx
  src/components/InputUpload/InputUpload.tsx
  src/components/PinEditSlideButton/PinEditSlideButton.styles.ts
  src/components/PinEditSlideButton/PinEditSlideButton.tsx
  src/components/SlideButton/SlideButton.style.ts
  src/components/index.ts
  src/components/modalViews/ConfirmModal/ConfirmModal.tsx
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/types/OriginDataType/Pin.ts
  src/types/Request/Post.ts
  src/types/Request/index.ts
  src/types/Response/Masil.ts
  src/types/Response/index.ts
Labels: enhancement

#155 [Feat] Post Create Page 레이아웃 작업
  public/sw.js.map
  public/swe-worker-development.js
  src/app/log/create/page.tsx
  src/app/log/record/LogRecord.model.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.model.tsx
  src/app/post/create/PostCreate.constants.ts
  src/app/post/create/PostCreate.controller.tsx
  src/app/post/create/PostCreate.styles.ts
  src/app/post/create/PostCreate.types.ts
  src/app/post/create/PostCreate.view.tsx
  src/app/post/create/components/PostPinEdit/PostPinEdit.controller.ts
  src/app/post/create/components/PostPinEdit/PostPinEdit.styles.ts
  src/app/post/create/components/PostPinEdit/PostPinEdit.view.tsx
  src/app/post/create/components/PostTextEdit/PostTextEdit.controller.ts
  src/app/post/create/components/PostTextEdit/PostTextEdit.styles.ts
  src/app/post/create/components/PostTextEdit/PostTextEdit.view.tsx
  src/app/post/create/components/PostTextEdit/components/PostContentEdit/PostContentEdit.tsx
  src/app/post/create/components/PostTextEdit/components/PostPublicEdit/PostPublicEdit.styles.ts
  src/app/post/create/components/PostTextEdit/components/PostPublicEdit/PostPublicEdit.tsx
  src/app/post/create/components/PostTextEdit/components/PostThumbnailEdit/PostThumbnailEdit.styles.ts
  src/app/post/create/components/PostTextEdit/components/PostThumbnailEdit/PostThumbnailEdit.tsx
  src/app/post/create/components/PostTextEdit/components/PostTitleEdit/PostTitleEdit.tsx
  src/app/post/create/components/PostTextEdit/components/index.ts
  src/app/post/create/components/index.ts
  src/app/post/create/context/PostCreateContext.tsx
  src/app/post/create/context/reducer/PostCreateReducer.ts
  src/app/post/create/page.tsx
  src/components/InputUpload/InputUpload.tsx
  src/components/PinEditSlideButton/PinEditSlideButton.styles.ts
  src/components/PinEditSlideButton/PinEditSlideButton.tsx
  src/components/SlideButton/SlideButton.style.ts
  src/components/icons/ArrowForward.tsx
  src/components/icons/DiaryFill.tsx
  src/components/icons/HomeFill.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/modalViews/ConfirmModal/ConfirmModal.styles.ts
  src/components/modalViews/ConfirmModal/ConfirmModal.tsx
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.tsx
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/components/modalViews/index.ts
  src/components/navigators/navInablePath.ts
  src/components/uiContext/UiContext.tsx
  src/stores/ui/types/modalType.ts
  src/types/OriginDataType/Pin.ts
  src/types/Request/Post.ts
  src/types/Request/index.ts
  src/types/Response/Masil.ts
  src/types/Response/index.ts
  yarn.lock
Labels: enhancement

#140 [Feat] Home 페이지 구현
  package.json
  src/app/home/Home.constants.ts
  src/app/home/Home.controller.tsx
  src/app/home/Home.styles.ts
  src/app/home/Home.types.ts
  src/app/home/Home.view.tsx
  src/app/home/api/fetchAirQuality.ts
  src/app/home/api/fetchNearbyStation.ts
  src/app/home/api/fetchWeatherForecast.ts
  src/app/home/components/MyLocationWeather/MyLocationWeather.styles.ts
  src/app/home/components/MyLocationWeather/MyLocationWeather.tsx
  src/app/home/components/MyLocationWeather/index.ts
  src/app/home/components/MyWalkRecord/MyWalkRecord.module.css
  src/app/home/components/MyWalkRecord/MyWalkRecord.tsx
  src/app/home/components/MyWalkRecord/index.ts
  src/app/home/components/Notification/Notification.tsx
  src/app/home/components/WalkList/WalkList.styles.ts
  src/app/home/components/WalkList/WalkList.tsx
  src/app/home/components/WalkList/index.ts
  src/app/home/components/WalkStartButton/WalkStartButton.tsx
  src/app/home/components/index.ts
  src/app/home/page.tsx
  src/app/home/utils/convertLatLonToGrid.ts
  src/app/home/utils/convertLatLonToTM.ts
  src/app/home/utils/getCurrentDateTime.ts
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/LogDetailCard/LogDetailCard.tsx
  src/components/LogDetailCard/index.ts
  src/components/icons/ClearSky.tsx
  src/components/icons/FineDust.tsx
  src/components/icons/Location.tsx
  src/components/icons/More.tsx
  src/components/icons/NotificationActive.tsx
  src/components/icons/NotificationOff.tsx
  src/components/icons/Overcast.tsx
  src/components/icons/PartlyCloudy.tsx
  src/components/icons/Rainy.tsx
  src/components/icons/Sleet.tsx
  src/components/icons/Snowy.tsx
  src/components/icons/index.ts
  src/stories/LogDetailCard.stories.tsx
  yarn.lock
Labels: enhancement

#152 [Refactoring] UserProfile 페이지 수정
  src/app/user/[id]/MyPage.constants.ts
  src/app/user/[id]/MyPage.controller.tsx
  src/app/user/[id]/MyPage.styles.ts
  src/app/user/[id]/MyPage.types.ts
  src/app/user/[id]/MyPage.view.tsx
  src/app/user/[id]/Mypage.constants.ts
  src/app/user/[id]/Mypage.controller.tsx
  src/app/user/[id]/Mypage.model.ts
  src/app/user/[id]/Mypage.types.ts
  src/app/user/[id]/components/MyPageSetting/MyPageSetting.tsx
  src/app/user/[id]/components/MyPageSetting/index.ts
  src/app/user/[id]/components/MyRecordList/MyRecordList.styles.ts
  src/app/user/[id]/components/MyRecordList/MyRecordList.tsx
  src/app/user/[id]/components/MyRecordList/index.ts
  src/app/user/[id]/components/MyRecordList/index.tsx
  src/app/user/[id]/components/UserInfo/UserInfo.styles.ts
  src/app/user/[id]/components/UserInfo/index.tsx
  src/app/user/[id]/components/UserProfileInfo/UserProfileInfo.styles.ts
  src/app/user/[id]/components/UserProfileInfo/UserProfileInfo.tsx
  src/app/user/[id]/components/UserProfileInfo/index.ts
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.styles.ts
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.tsx
  src/app/user/[id]/components/UserWalkRecord/index.ts
  src/app/user/[id]/components/UserWalkRecord/index.tsx
  src/app/user/[id]/components/index.ts
  src/app/user/[id]/page.tsx
  src/components/ListCard/ListCard.tsx
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/LogDetailCard/LogDetailCard.tsx
  src/components/LogSimpleCard/LogSimpleCard.style.ts
  src/components/LogSimpleCard/LogSimpleCard.tsx
  src/components/LogSimpleCard/index.ts
  src/components/LogSimpleCard/index.tsx
  src/components/icons/Camera.tsx
  src/components/icons/Setting.tsx
  src/components/modalViews/ProfileEditModal/ProfileEditModal.styles.ts
  src/components/modalViews/ProfileEditModal/ProfileEditModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/stores/ui/types/modalType.ts
  src/stories/LogDetailCard.stories.tsx
  src/stories/LogSimpleCard.stories.tsx
  src/utils/calculateAge.ts
  src/utils/calculateWalkingCalories.ts
  src/utils/convertDateToYearMonthDay.ts
  src/utils/convertMeter.ts
  src/utils/convertSeconds.ts
  src/utils/index.ts
Labels: refactor

#178 [Fix] HomePage 긴급 수정
  src/app/home/Home.constants.ts
  src/app/home/Home.controller.tsx
  src/app/home/Home.types.ts
  src/app/home/Home.view.tsx
  src/app/home/components/MyWalkRecord/MyWalkRecord.tsx
  src/app/home/components/WalkList/WalkList.tsx
  src/components/LogDetailCard/LogDetailCard.tsx
  src/utils/calculateWalkingCalories.ts
Labels: bug

#180 [Fix] HomePage 긴급수정
  next.config.mjs
  src/app/home/Home.constants.ts
  src/app/home/Home.types.ts
Labels: bug

#176 [Feat] LogRecord API 연결 작업
  next.config.mjs
  public/sw.js.map
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.model.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/app/log/record/components/index.ts
  src/app/log/record/context/LogRecordContext.tsx
  src/app/log/record/page.tsx
  src/app/user/[id]/setting/edit/UserEdit.controller.tsx
  src/app/user/[id]/setting/edit/UserEdit.styles.ts
  src/app/user/[id]/setting/edit/UserEdit.view.tsx
  src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.tsx
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/lib/api/endPoints.ts
  src/lib/api/image/client.ts
  src/lib/api/masil/client.ts
  src/lib/api/queryKeys.ts
  src/lib/hooks/useImageUpload.ts
  src/types/Request/Masils.ts
  src/types/Response/Masil.ts
  src/utils/drawPath.ts
  yarn.lock
Labels: enhancement

#184 [Fix] MyPage 긴급수정
  src/app/user/[id]/MyPage.constants.ts
  src/app/user/[id]/MyPage.controller.tsx
  src/app/user/[id]/MyPage.types.ts
  src/app/user/[id]/MyPage.view.tsx
  src/app/user/[id]/components/MyRecordList/MyRecordList.tsx
  src/app/user/[id]/components/UserProfileInfo/UserProfileInfo.tsx
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.tsx
  src/components/icons/Camera.tsx
  src/stories/LogSimpleCard.stories.tsx
Labels: bug

#165 [Feat] Log View 페이지 구현
  src/app/log/[id]/Log.constants.ts
  src/app/log/[id]/Log.controller.tsx
  src/app/log/[id]/Log.model.ts
  src/app/log/[id]/Log.styles.ts
  src/app/log/[id]/Log.types.ts
  src/app/log/[id]/Log.view.tsx
  src/app/log/[id]/components/LogKebabMenu/LogKebabMenu.tsx
  src/app/log/[id]/components/LogMapSection/LogMapSection.styles.ts
  src/app/log/[id]/components/LogMapSection/LogMapSection.tsx
  src/app/log/[id]/components/LogMemo/LogMemo.styles.ts
  src/app/log/[id]/components/LogMemo/LogMemo.tsx
  src/app/log/[id]/components/LogPin/LogPin.styles.ts
  src/app/log/[id]/components/LogPin/LogPin.tsx
  src/app/log/[id]/components/index.ts
  src/app/log/[id]/page.tsx
  src/app/mate/[id]/components/MateInfo/components/MateDropDownMenu/MateDropDownMenu.styles.ts
  src/app/mate/[id]/components/MateInfo/components/MateDropDownMenu/MateDropDownMenu.tsx
  src/components/Divider/Divider.tsx
  src/components/PinDetailCard/PinDetailCard.styles.ts
  src/components/PinDetailCard/PinDetailCard.tsx
  src/components/Tab/Tab.styles.ts
  src/components/icons/KebabMenu.tsx
  src/types/Response/User.ts
  src/utils/convertFormatDate.ts
Labels: enhancement

#185 [Feat] 산책일지 페이지 구현 (API)
  .gitignore
  package.json
  public/sw.js.map
  public/swe-worker-4da67dda9bc18c53.js
  public/swe-worker-development.js
  public/workbox-c06b064f.js
  src/app/diary/[id]/MasilDiary.controller.ts
  src/app/diary/[id]/MasilDiary.styles.ts
  src/app/diary/[id]/MasilDiary.type.ts
  src/app/diary/[id]/MasilDiary.view.tsx
  src/app/diary/[id]/components/DiaryItem/DiaryItem.styles.ts
  src/app/diary/[id]/components/DiaryItem/DiaryItem.tsx
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.styles.ts
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.tsx
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.styles.ts
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.tsx
  src/app/diary/[id]/page.tsx
  src/app/user/[id]/diary/page.tsx
  src/app/user/[id]/reward/page.tsx
  src/components/ShadcnUi/ui/button.tsx
  src/components/ShadcnUi/ui/calendar.tsx
  src/components/ShadcnUi/ui/daylessCalender.tsx
  src/components/ShadcnUi/ui/toast.tsx
  src/components/ShadcnUi/ui/toaster.tsx
  src/components/ShadcnUi/ui/useToast.ts
  src/components/Tab/Tab.styles.ts
  src/components/icons/Location.tsx
  src/components/icons/Return.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.constants.tsx
  src/components/navigators/TopNavigator/TopNavigator.styles.ts
  src/lib/api/MasilDiary/getMasilsByPeriod.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/types/Response/Masil.ts
  yarn.lock
Labels: enhancement

#194 [Fix] deploy 오류 수정
  package.json
  src/app/auth/kakao/page.tsx
  src/app/diary/[id]/MasilDiary.view.tsx
  src/app/home/Home.constants.ts
  src/app/log/[id]/Log.view.tsx
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/policy/age/page.mdx
  src/app/policy/layout.tsx
  src/app/policy/location/page.mdx
  src/app/policy/personal/page.mdx
  src/app/signin/components/SignInHelper/index.ts
  src/app/signin/components/index.ts
  src/app/signin/page.tsx
  src/app/signin/sections/index.ts
  src/app/signup/SignUp.controller.tsx
  src/app/signup/SignUp.model.tsx
  src/app/signup/SignUp.styles.ts
  src/app/signup/SignUp.view.tsx
  src/app/signup/components/SignUpHelper/SignUpHelper.style.ts
  src/app/signup/components/SignUpHelper/SignUpHelper.tsx
  src/app/signup/components/SignUpHelper/index.ts
  src/app/signup/components/StepButton/StepButton.tsx
  src/app/signup/components/StepButton/index.ts
  src/app/signup/components/index.ts
  src/app/signup/error.tsx
  src/app/signup/page.tsx
  src/app/signup/sections/SignUpStep1.tsx
  src/app/signup/sections/SignUpStep2.tsx
  src/app/signup/sections/SignUpStep3.tsx
  src/app/signup/sections/SignUpStep4.tsx
  src/app/signup/sections/index.ts
  src/components/LogDetailCard/LogDetailCard.tsx
  src/components/icons/KebabMenu.tsx
  src/components/navigators/navInablePath.ts
  src/components/windowViews/Policy.tsx
  src/components/windowViews/index.ts
  src/lib/AuthLoader.tsx
  src/middleware.ts
  src/stores/useMeStore.ts
  src/stories/DotIndicator.stories.tsx
  src/utils/calculateWalkingCalories.ts
  yarn.lock
Labels: bug

#195 [Feat] 로그아웃 기능 구현
  src/app/user/[id]/setting/UserSetting.controller.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.controller.ts
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.controller.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.view.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.controller.ts
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.controller.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.view.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.controller.ts
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.controller.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.view.tsx
  src/app/user/[id]/setting/components/index.ts
  src/app/user/[id]/setting/page.tsx
  src/components/modalViews/ConfirmModal/ConfirmModal.styles.ts
  src/components/modalViews/ConfirmModal/ConfirmModal.tsx
  src/components/modalViews/DeployAlertModal/AnimationData.json
  src/components/modalViews/DeployAlertModal/DeployAlertModal.styles.ts
  src/components/modalViews/DeployAlertModal/DeployAlertModal.tsx
  src/components/uiContext/UiContext.tsx
  src/stores/ui/types/modalType.ts
Labels: enhancement

#202 [Fix] Explore Map center 에러 해결
  src/app/api/auth/[...nextauth]/options.ts
  src/app/explore/sections/BottomSheetSection/BottomSheetSection.tsx
  src/app/explore/sections/MapSection/MapSection.tsx
  src/styles/GlobalStyle.tsx
Labels: bug

#188 [Feat] LogRecord 추가 API 연결
  src/app/explore/sections/MapSection/MapSection.tsx
  src/app/log/record/LogRecord.controller.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/context/LogRecordContext.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
  src/app/log/record/page.tsx
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/NavigationPin/NavigationPin.styles.ts
  src/components/MasilMap/components/NavigationPin/NavigationPin.tsx
  src/components/MasilMap/components/index.ts
  src/components/icons/MapPin.tsx
  src/components/icons/index.ts
  src/components/modalViews/MateMapModal/MateCreateMapModal/MateCreateMapModal.tsx
  src/components/modalViews/MateMapModal/MateLocationMapModal/MapLocationMapModal.tsx
  src/components/modalViews/PinDetailModal/PinDetailModal.styles.ts
  src/components/modalViews/PinDetailModal/PinDetailModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/lib/api/queryKeys.ts
  src/stores/ui/types/modalType.ts
  src/styles/theme.ts
  yarn.lock
Labels: enhancement

#181 [Feat] 메이트 구인 페이지 구현
  package.json
  src/app/mate/create/MateCreate.constants.ts
  src/app/mate/create/MateCreate.controller.tsx
  src/app/mate/create/MateCreate.model.tsx
  src/app/mate/create/MateCreate.styles.ts
  src/app/mate/create/MateCreate.view.tsx
  src/app/mate/create/components/CalendarDatePicker/CalendarDatePicker.styles.tsx
  src/app/mate/create/components/CalendarDatePicker/CalendarDatePicker.tsx
  src/app/mate/create/components/CalendarDatePicker/index.tsx
  src/app/mate/create/components/OptionTimePicker/OptionTimePicker.styles.ts
  src/app/mate/create/components/OptionTimePicker/OptionTimePicker.tsx
  src/app/mate/create/components/OptionTimePicker/index.tsx
  src/app/mate/create/components/index.tsx
  src/app/mate/create/page.tsx
Labels: enhancement

#205 [Fix] 산책일지 페이지 버그 수정
  src/app/diary/[id]/MasilDiary.controller.ts
  src/app/diary/[id]/components/DiaryItem/DiaryItem.styles.ts
  src/app/diary/[id]/components/DiaryItem/DiaryItem.tsx
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.tsx
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
  src/components/ShadcnUi/ui/calendar.tsx
Labels: bug

#197 [Feat] LogView 페이지 (API 연동)
  src/app/log/[id]/Log.constants.ts
  src/app/log/[id]/Log.controller.tsx
  src/app/log/[id]/Log.model.ts
  src/app/log/[id]/Log.styles.ts
  src/app/log/[id]/Log.types.ts
  src/app/log/[id]/Log.view.tsx
  src/app/log/[id]/components/LogMemo/LogMemo.tsx
  src/app/log/[id]/components/index.ts
  src/app/log/[id]/page.tsx
  src/app/log/[id]/sections/LogMapSection/LogMapSection.styles.ts
  src/app/log/[id]/sections/LogMapSection/LogMapSection.tsx
  src/app/log/[id]/sections/index.ts
  src/components/PinDetailCard/PinDetailCard.styles.ts
  src/components/PinDetailCard/PinDetailCard.tsx
  src/components/Tab/Tab.tsx
  src/lib/api/masil/server.ts
  src/lib/api/serverRootAPI.ts
Labels: enhancement

#213 [Fix] 산책일지 BottomSheet에 데이터가 제대로 들어가지 않는 문제
  src/app/diary/[id]/MasilDiary.controller.ts
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.tsx
  yarn.lock
Labels: bug

#214 [ Fix ] GPS 거리값 수정
  src/app/log/record/context/LogRecordContext.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
Labels: enhancement

#190 [Feat] PostView 페이지 구현 (API 연동)
  src/app/log/[id]/Log.view.tsx
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/mate/[id]/components/MateInfo/components/MateDropDownMenu/MateDropDownMenu.tsx
  src/app/mate/[id]/components/MateInfo/components/index.ts
  src/app/post/[id]/Post.constants.ts
  src/app/post/[id]/Post.controller.tsx
  src/app/post/[id]/Post.model.ts
  src/app/post/[id]/Post.styles.ts
  src/app/post/[id]/Post.types.ts
  src/app/post/[id]/Post.view.tsx
  src/app/post/[id]/components/PostKebabMenu/PostKebabMenu.tsx
  src/app/post/[id]/components/PostMate/PostMate.styles.ts
  src/app/post/[id]/components/PostMate/PostMate.tsx
  src/app/post/[id]/components/PostMemo/PostMemo.styles.ts
  src/app/post/[id]/components/PostMemo/PostMemo.tsx
  src/app/post/[id]/components/PostPin/PostPin.styles.ts
  src/app/post/[id]/components/PostPin/PostPin.tsx
  src/app/post/[id]/components/index.ts
  src/app/post/[id]/page.tsx
  src/app/post/[id]/sections/PostMapSection/PostMapSection.styles.ts
  src/app/post/[id]/sections/PostMapSection/PostMapSection.tsx
  src/app/post/[id]/sections/index.ts
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/index.ts
  src/components/DropDownMenu/DropDownMenu.styles.ts
  src/components/DropDownMenu/DropDownMenu.tsx
  src/components/DropDownMenu/index.ts
  src/components/LogSimpleCard/LogSimpleCard.style.ts
  src/components/LogSimpleCard/LogSimpleCard.tsx
  src/components/MateCard/MateCard.styles.ts
  src/components/MateCard/MateCard.tsx
  src/components/MateCard/index.ts
  src/components/PinDetailCard/PinDetailCard.styles.ts
  src/components/PinDetailCard/PinDetailCard.tsx
  src/components/Tab/Tab.styles.ts
  src/components/index.ts
  src/lib/api/Post/server.ts
Labels: enhancement

#211 [Feat] Skeleton UI 기초 적용
  src/app/diary/[id]/MasilDiary.view.tsx
  src/app/diary/[id]/page.tsx
  src/app/home/page.tsx
  src/app/not-found.tsx
  src/app/user/[id]/page.tsx
  src/components/skeletons.tsx
  tailwind.config.ts
Labels: enhancement

#217 [Fix] Carousel bug fix
  src/app/log/[id]/components/LogPin/LogPin.tsx
  src/app/post/[id]/components/PostPin/PostPin.tsx
  src/components/Button/Button.tsx
  src/components/DotIndicator/DotIndicator.tsx
  src/components/OrderTab/OrderTab.tsx
Labels: bug

#218 [Fix] server component 에서 client component 를 호출할 때 발생하는 에러 수정
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/components/Avatar/Avatar.styles.ts
  src/components/BottomSheet/SheetBackdrop.tsx
  src/components/BottomSheet/SheetContainer.tsx
  src/components/BottomSheet/SheetContent.tsx
  src/components/BottomSheet/SheetHeader.tsx
  src/components/BottomSheet/SheetScroller.tsx
  src/components/BottomSheet/context.tsx
  src/components/BottomSheet/hooks.tsx
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/sheet.tsx
  src/components/BottomSheet/types.tsx
  src/components/Button/RippleEffect/RippleEffect.tsx
  src/components/DropDownMenu/DropDownMenu.styles.ts
  src/components/Input/Input.styles.ts
  src/components/Input/Input.tsx
  src/components/InputLabel/InputLabel.styles.ts
  src/components/InputRadio/InputRadio.styles.ts
  src/components/InputUpload/InputUpload.styles.ts
  src/components/ListCard/ListCard.styles.ts
  src/components/LoadingSpinner/LoadingSpinner.styles.ts
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/PinDetailCard/PinDetailCard.styles.ts
  src/components/PinEditSlideButton/PinEditSlideButton.styles.ts
  src/components/SlideButton/SlideButton.style.ts
  src/components/StepLayout/StepLayout.tsx
  src/components/Tab/Tab.styles.ts
  src/components/Tab/Tab.tsx
  src/components/Textarea/Textarea.styles.ts
  src/components/UserEditInput/UserEditInput.styles.ts
  src/components/UserIntensityItem/UserIntensityItem.styles.ts
  yarn.lock
Labels: bug

#206 [Feat] Explore List API 연결
  src/app/diary/[id]/MasilDiary.view.tsx
  src/app/explore/Explore.controller.tsx
  src/app/explore/Explore.model.tsx
  src/app/explore/sections/BottomSheetSection/BottomSheetSection.tsx
  src/app/explore/sections/ListSection/ListSection.styles.ts
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/explore/sections/MapSection/MapSection.styles.ts
  src/app/explore/sections/MapSection/MapSection.tsx
  src/app/log/[id]/Log.view.tsx
  src/app/more/MoreList.view.tsx
  src/components/ListCard/ListCard.styles.ts
  src/components/ListCard/ListCard.tsx
  src/components/Tab/Tab.tsx
  src/lib/AuthLoader.tsx
  src/lib/api/Post/client.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/types/OriginDataType/GeoPosition.ts
  src/types/OriginDataType/Post.ts
  src/types/Request/Post.ts
  src/types/Response/Post.ts
  src/utils/parseLocation.ts
Labels: enhancement

#224 [refactor] SignUp step 추가
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/explore/sections/MapSection/MapSection.tsx
  src/app/signup/SignUp.controller.tsx
  src/app/signup/SignUp.styles.ts
  src/app/signup/SignUp.view.tsx
  src/app/signup/components/SignUpHelper/SignUpHelper.tsx
  src/app/signup/sections/SignUpStep1.tsx
  src/app/signup/sections/SignUpStep2.tsx
  src/app/signup/sections/SignUpStep3.tsx
  src/app/signup/sections/SignUpStep4.tsx
  src/app/signup/sections/SignUpStep5.tsx
  src/app/signup/sections/index.ts
Labels: refactor

#228 [Feat] 마이페이지 API 연결
  next.config.mjs
  src/app/diary/[id]/MasilDiary.controller.ts
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.styles.ts
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.tsx
  src/app/user/[id]/MyPage.constants.ts
  src/app/user/[id]/MyPage.controller.tsx
  src/app/user/[id]/MyPage.styles.ts
  src/app/user/[id]/MyPage.types.ts
  src/app/user/[id]/MyPage.view.tsx
  src/app/user/[id]/components/MyRecordList/MyRecordList.styles.ts
  src/app/user/[id]/components/MyRecordList/MyRecordList.tsx
  src/app/user/[id]/components/UserProfileInfo/UserProfileInfo.styles.ts
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.styles.ts
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.tsx
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/LogDetailCard/LogDetailCard.tsx
  src/components/LogSimpleCard/LogSimpleCard.style.ts
  src/components/LogSimpleCard/LogSimpleCard.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.constants.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.styles.ts
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/lib/api/MasilDiary/getMasilsByPeriod.ts
  src/lib/api/Post/server.ts
  src/lib/api/User/server.ts
  src/lib/api/endPoints.ts
  src/lib/api/masil/server.ts
  src/types/Response/Masil.ts
  src/types/Response/Post.ts
  src/types/Response/User.ts
Labels: enhancement

#226 [Refactor] Explore List Refactor
  src/app/explore/Explore.controller.tsx
  src/app/explore/Explore.model.tsx
  src/app/explore/components/SearchBar/SearchBar.tsx
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/explore/sections/MapSection/MapSection.tsx
  src/app/post/create/PostCreate.styles.ts
  src/app/post/create/components/PostPinEdit/PostPinEdit.view.tsx
  src/app/post/create/components/PostTextEdit/PostTextEdit.view.tsx
  src/app/user/[id]/setting/edit/UserEdit.styles.ts
  src/app/user/[id]/setting/edit/UserEdit.view.tsx
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.styles.ts
  src/components/UserIntensityItem/UserIntensityItem.styles.ts
  src/components/UserIntensityItem/UserIntensityItem.tsx
  src/lib/api/Post/client.ts
  src/middleware.ts
  src/styles/theme.ts
  src/types/Request/Post.ts
Labels: refactor

#227 [Feat] User Edit / Setting API 연결
  src/app/explore/sections/MapSection/MapSection.tsx
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/log/record/context/LogRecordContext.tsx
  src/app/post/create/context/PostCreateContext.tsx
  src/app/post/create/page.tsx
  src/app/user/[id]/setting/UserSetting.styles.ts
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/SettingContent/SettingContent.styles.ts
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.controller.ts
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.view.tsx
  src/app/user/[id]/setting/edit/UserEdit.controller.ts
  src/app/user/[id]/setting/edit/UserEdit.controller.tsx
  src/app/user/[id]/setting/edit/UserEdit.model.ts
  src/app/user/[id]/setting/edit/UserEdit.styles.ts
  src/app/user/[id]/setting/edit/UserEdit.types.ts
  src/app/user/[id]/setting/edit/UserEdit.view.tsx
  src/app/user/[id]/setting/edit/components/EditBirthDate/EditBirthDate.tsx
  src/app/user/[id]/setting/edit/components/EditBodyInfo/EditBodyInfo.tsx
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.styles.ts
  src/app/user/[id]/setting/edit/components/EditIntensity/EditIntensity.tsx
  src/app/user/[id]/setting/edit/components/EditNickname/EditNickname.tsx
  src/app/user/[id]/setting/edit/components/EditSex/EditSex.tsx
  src/app/user/[id]/setting/edit/page.tsx
  src/components/Divider/Divider.tsx
  src/components/InputRadio/InputRadio.styles.ts
  src/components/LoadingSpinner/LoadingSpinner.styles.ts
  src/components/UserEditInput/UserEditInput.styles.ts
  src/components/UserIntensityItem/UserIntensityItem.styles.ts
  src/components/modalViews/AnimationAlertModal/AlertAnimationData.json
  src/components/modalViews/AnimationAlertModal/AnimationAlertModal.styles.ts
  src/components/modalViews/AnimationAlertModal/AnimationAlertModal.tsx
  src/components/modalViews/DoneModal/DoneModal.styles.ts
  src/components/modalViews/DoneModal/DoneModal.tsx
  src/components/modalViews/DoneModal/animationData.json
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.styles.ts
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/hooks/useGeoLocationUtils.ts
  src/lib/api/User/client.ts
  src/lib/api/User/server.ts
  src/lib/api/clientRootAPI.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/stores/ui/types/modalType.ts
  src/types/OriginDataType/IntensityOption.ts
  src/types/Request/User.ts
  src/types/Response/User.ts
  yarn.lock
Labels: enhancement

#221 [Feat] MateCreate 썸네일, 위치 모달 추가
  src/app/mate/create/MateCreate.constants.ts
  src/app/mate/create/MateCreate.controller.tsx
  src/app/mate/create/MateCreate.model.tsx
  src/app/mate/create/MateCreate.styles.ts
  src/app/mate/create/MateCreate.view.tsx
  src/components/modalViews/MateMapModal/MateCreateMapModal/MateCreateMapModal.tsx
Labels: enhancement

#231 [Refactoring] LogRecord , Mate 리팩토링
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.styles.ts
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.styles.ts
  src/app/mate/[id]/components/MateMap/MateMap.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.controller.ts
  src/components/modalViews/ConfirmModal/ConfirmAnimationData.json
  src/components/modalViews/ConfirmModal/ConfirmModal.styles.ts
  src/components/modalViews/ConfirmModal/ConfirmModal.tsx
  src/components/modalViews/PinEditModal/LoadingAnimationData.json
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  yarn.lock
Labels: enhancement, refactor

#235 [Fix] deploy fix
  package.json
  public/manifest.json
  src/app/Main.view.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Avatar/Avatar.tsx
  src/components/BottomSheet/SheetContainer.tsx
  src/components/BottomSheet/styles.ts
  src/components/navigators/BottomNavigator/BottomNavigator.styles.ts
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/middleware.ts
  src/styles/theme.ts
  yarn.lock
Labels: bug

#229 [Feat] Home 페이지 API 연동
  src/app/home/Home.constants.ts
  src/app/home/Home.controller.tsx
  src/app/home/Home.styles.ts
  src/app/home/Home.types.ts
  src/app/home/Home.view.tsx
  src/app/home/api/fetchNearbyStation.ts
  src/app/home/api/fetchWeatherForecast.ts
  src/app/home/components/MyLocationWeather/MyLocationWeather.tsx
  src/app/home/components/MyWalkRecord/MyWalkRecord.tsx
  src/app/home/components/Notification/Notification.tsx
  src/app/home/components/Notification/index.ts
  src/app/home/components/WalkList/WalkList.styles.ts
  src/app/home/components/WalkList/WalkList.tsx
  src/app/home/components/WalkList/components/MyLikeWalkingTrails/MyLikeWalkingTrails.style.ts
  src/app/home/components/WalkList/components/MyLikeWalkingTrails/MyLikeWalkingTrails.tsx
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/PopularTrailsInOurTown.styles.ts
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/PopularTrailsInOurTown.tsx
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/components/PopularWalkList.styles.ts
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/components/PopularWalkList.tsx
  src/app/home/components/WalkList/components/PopularWalkingTrails/PopularWalkingTrails.style.ts
  src/app/home/components/WalkList/components/PopularWalkingTrails/PopularWalkingTrails.tsx
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.styles.ts
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/app/home/components/WalkStartButton/WalkStartButton.tsx
  src/app/home/components/WalkStartButton/index.ts
  src/app/home/components/index.ts
  src/app/home/page.tsx
  src/app/home/utils/getDetailedAddress.ts
  src/app/home/utils/index.ts
  src/app/home/utils/showErrorMessage.ts
  src/app/more/lib/fetchMoreList.ts
  src/components/skeletons.tsx
  src/lib/api/home/client.ts
  src/lib/api/home/server.ts
  src/lib/api/queryKeys.ts
  src/stores/useUserLocationStore.ts
  src/types/OriginDataType/Location.ts
  src/types/Response/Post.ts
  src/utils/convertMeter.ts
  src/utils/convertSeconds.ts
Labels: enhancement

#240 [Deploy] 배포 이전 개선 사항 반영
  src/app/explore/sections/BottomSheetSection/BottomSheetSection.tsx
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.styles.ts
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/app/log/[id]/Log.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/post/[id]/Post.styles.ts
  src/app/post/create/PostCreate.styles.ts
  src/app/post/create/PostCreate.view.tsx
  src/app/user/[id]/MyPage.styles.ts
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/SettingContent/SettingContent.styles.ts
  src/components/Avatar/Avatar.tsx
  src/components/InputUpload/InputUpload.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.styles.ts
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  yarn.lock
Labels: bug, enhancement, refactor

#249 [Fix] auth service token 에러 픽스
  src/app/api/auth/[...nextauth]/options.ts
  src/lib/AuthLoader.tsx
  src/lib/api/User/server.ts
  src/lib/api/serverRootAPI.ts
  src/middleware.ts
Labels: bug

#250 [Refactor] react-virtualized 도입
  package.json
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/signup/SignUp.controller.tsx
  src/app/signup/SignUp.model.tsx
  src/app/signup/sections/SignUpStep1.tsx
  src/app/signup/sections/SignUpStep2.tsx
  src/components/OrderTab/OrderTab.styles.ts
  src/components/UserEditInput/UserEditInput.tsx
  src/lib/constants/userConstants.ts
  yarn.lock
Labels: refactor

#254 [Refactoring] LogRecord Page
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/log/record/context/LogRecordContext.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
  src/app/log/record/utils/checkMasilError.ts
  src/app/post/create/PostCreate.controller.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/components/modalViews/PinDetailModal/PinDetailModal.styles.ts
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/hooks/useGeoLocationUtils.ts
  src/lib/api/axios/axiosConfig.ts
  src/lib/api/clientRootAPI.ts
Labels: refactor

#255 [Refactor] Home Page 및 LogDetailCard 컴포넌트 수정
  src/app/home/Home.styles.ts
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/components/PopularWalkList.tsx
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/LogDetailCard/LogDetailCard.tsx
  src/components/skeletons.tsx
Labels: refactor

#247 [Fix] PostView 페이지 오류 수정
  src/app/post/[id]/Post.controller.tsx
  src/app/post/[id]/Post.styles.ts
  src/app/post/[id]/Post.view.tsx
  src/app/post/[id]/components/PostKebabMenu/PostKebabMenu.tsx
  src/app/post/[id]/components/PostMemo/PostMemo.styles.ts
  src/app/post/[id]/components/PostMemo/PostMemo.tsx
  src/app/post/[id]/components/PostPin/PostPin.styles.ts
  src/app/post/[id]/components/PostPin/PostPin.tsx
  src/components/PinDetailCard/PinDetailCard.styles.ts
  src/components/PinDetailCard/PinDetailCard.tsx
Labels: bug

#245 [Fix] LogView 페이지 오류 수정
  src/app/log/[id]/Log.controller.tsx
  src/app/log/[id]/Log.styles.ts
  src/app/log/[id]/Log.view.tsx
  src/app/log/[id]/components/LogKebabMenu/LogKebabMenu.tsx
  src/app/log/[id]/components/LogMemo/LogMemo.styles.ts
  src/app/log/[id]/components/LogPin/LogPin.styles.ts
  src/app/log/[id]/components/LogPin/LogPin.tsx
Labels: bug

#257 [Refactor] more page api 연결
  src/app/explore/Explore.controller.tsx
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/home/Home.styles.ts
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/app/more/MoreList.constants.ts
  src/app/more/MoreList.controller.tsx
  src/app/more/MoreList.view.tsx
  src/app/more/page.tsx
  src/app/user/[id]/page.tsx
  src/components/skeletons.tsx
  src/lib/api/Post/client.ts
  src/types/Request/Post.ts
Labels: refactor

#258 [Fix] 더보기 버튼 처리 수정
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
Labels: bug

#259 [Fix] PinDetailCard 수정으로 발생한 오류 수정
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/components/PinDetailCard/PinDetailCard.tsx
Labels: bug

#266 [Fix] 산책일지, 마이페이지 버그 수정
  src/app/diary/[id]/MasilDiary.view.tsx
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.tsx
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/user/[id]/MyPage.styles.ts
  src/app/user/[id]/components/MyRecordList/MyRecordList.styles.ts
  src/app/user/[id]/components/UserProfileInfo/UserProfileInfo.tsx
Labels: bug

#268 [ Refactor ] morepage api v2
  src/app/explore/Explore.controller.tsx
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/home/Home.constants.ts
  src/app/more/MoreList.controller.tsx
  src/app/more/MoreList.view.tsx
  src/app/more/SortTab/SortTab.tsx
  src/app/more/page.tsx
  src/app/user/[id]/MyPage.controller.tsx
  src/app/user/[id]/components/MyRecordList/MyRecordList.tsx
  src/lib/api/Post/client.ts
  src/types/Request/Post.ts
  tailwind.config.ts
Labels: refactor

#264 [Refactor] LogView, PostView 페이지 추가 수정
  src/app/log/[id]/Log.types.ts
  src/app/log/[id]/Log.view.tsx
  src/app/log/[id]/components/LogMemo/LogMemo.styles.ts
  src/app/log/[id]/components/LogMemo/LogMemo.tsx
  src/app/post/[id]/Post.types.ts
  src/app/post/[id]/Post.view.tsx
  src/app/post/[id]/components/PostMemo/PostMemo.styles.ts
  src/app/post/[id]/components/PostMemo/PostMemo.tsx
  src/components/Avatar/Avatar.styles.ts
  src/components/Avatar/Avatar.tsx
  src/components/icons/ViewIcon.tsx
  src/components/icons/index.ts
  src/lib/api/User/client.ts
  src/lib/api/queryKeys.ts
  src/types/Response/User.ts
Labels: refactor

#269 [Refactor] HomePage 추가 수정
  src/app/home/Home.styles.ts
  src/app/home/Home.view.tsx
  src/app/home/components/MyInfo/MyInfo.styles.ts
  src/app/home/components/MyInfo/MyInfo.tsx
  src/app/home/components/MyWalkRecord/MyWalkRecord.module.css
  src/app/home/components/WalkStartButton/WalkStartButton.tsx
  tailwind.config.ts
Labels: refactor

#272 [hotfix] Home 페이지 미세먼지 데이터에 대한 예외 처리 추가
  src/app/home/components/MyLocationWeather/MyLocationWeather.tsx
Labels: bug

#274 [Feat] PostView 페이지 (Mate API 추가)
  src/app/home/api/fetchAirQuality.ts
  src/app/home/api/fetchNearbyStation.ts
  src/app/home/api/fetchWeatherForecast.ts
  src/app/log/[id]/Log.styles.ts
  src/app/post/[id]/Post.controller.tsx
  src/app/post/[id]/Post.model.ts
  src/app/post/[id]/Post.styles.ts
  src/app/post/[id]/Post.types.ts
  src/app/post/[id]/Post.view.tsx
  src/app/post/[id]/components/PostMate/PostMate.styles.ts
  src/app/post/[id]/components/PostMate/PostMate.tsx
  src/app/post/[id]/components/PostPin/PostPin.styles.ts
  src/app/post/[id]/page.tsx
  src/lib/api/Mate/server.ts
  src/types/Response/mate.ts
Labels: enhancement

#278 [FIx] 미 사용 상수 코드로 인한 빌드 실패 개선
  src/app/post/[id]/Post.constants.ts
  yarn.lock
Labels: bug

#280 [refactor] auth refresh token API 연결
  d.types/next-auth.d.ts
  package.json
  src/app/Main.model.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/auth/kakao/Kakao.tsx
  src/app/auth/kakao/page.tsx
  src/lib/api/Test/serverTest.ts
  src/lib/api/Test/test.ts
  src/lib/api/User/client.ts
  src/lib/api/User/server.ts
  src/lib/api/axios/axiosConfig.ts
  src/lib/api/endPoints.ts
  src/middleware.ts
  src/types/Request/User.ts
  src/types/Response/User.ts
  yarn.lock
Labels: refactor

#282 [Feat] Mate 신청 수락 거절 API
  src/app/mate/[id]/components/MateInfo/MateInfo.styles.ts
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.tsx
  src/app/mate/[id]/components/MateInfo/components/MateDropDownMenuWrapper/MateDropDownMenuWrapper.tsx
  src/app/mate/[id]/components/MateMap/MateMap.tsx
  src/app/mate/[id]/components/MateMembers/MateMembers.tsx
  src/app/mate/[id]/components/MateMembers/components/MemberItem/MemberItem.tsx
  src/app/mate/[id]/components/MateMembers/components/MembersList/MembersList.tsx
  src/app/mate/[id]/error.tsx
  src/app/mate/[id]/hooks/index.ts
  src/app/mate/[id]/hooks/useAcceptParticipant.ts
  src/app/mate/[id]/hooks/useCancelParticipant.ts
  src/app/mate/[id]/hooks/useRequestParticipant.ts
  src/app/mate/[id]/page.tsx
  src/assets/Maesil_Mascot.png
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
  src/components/MasilMap/components/MatePointPin/MatePointPin.styles.ts
  src/components/MasilMap/components/MatePointPin/MatePointPin.tsx
  src/components/MasilMap/components/index.ts
  src/components/modalViews/MateParticipantModal/MateParticipantModal.styles.ts
  src/components/modalViews/MateParticipantModal/MateParticipantModal.tsx
  src/components/modalViews/MateRequestModal/MateRequestModal.styles.ts
  src/components/modalViews/MateRequestModal/MateRequestModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/lib/api/Mate/client.ts
  src/lib/api/Mate/server.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/lib/utils/checkErrorCode.ts
  src/stores/ui/types/modalType.ts
  src/types/OriginDataType/Mate.ts
  yarn.lock
Labels: enhancement

#284 [Refactor] auth refresh v2
  src/app/api/auth/[...nextauth]/options.ts
  src/lib/AuthContext.tsx
  src/lib/api/User/server.ts
  src/middleware.ts
Labels: refactor

#286 🐛fix: useCallback hook rule 위반
  src/app/explore/sections/ListSection/ListSection.tsx
  src/app/more/MoreList.view.tsx
Labels: bug

#291 [Refactor] splash page SSC CSC 분리 및 카카오 로그인 버튼 가이드 형식 적용
  src/app/(main)/Main.module.css
  src/app/(main)/Main.styles.ts
  src/app/(main)/Main.view.tsx
  src/app/(main)/components/AuthButton.styles.ts
  src/app/(main)/components/AuthButton.tsx
  src/app/Main.controller.tsx
  src/app/Main.model.tsx
  src/app/Main.styles.ts
  src/app/Main.view.tsx
  src/app/page.tsx
  src/app/signup/components/StepButton/StepButton.tsx
  src/components/icons/Message.tsx
  src/components/icons/Moon.tsx
  src/components/icons/Star.tsx
  src/components/icons/Sun.tsx
  src/components/icons/index.ts
  src/lib/api/User/client.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  tailwind.config.ts
Labels: refactor

#289 [Refactoring] LogRecord 개선 및 영상 작업을 위한 수정
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/context/reducer/LogRecordReducer.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
  src/lib/utils/checkErrorCode.ts
Labels: enhancement

#292 [Refactor] MyPage, Home 개인 산책 일지 디자인 통일화
  next.config.mjs
  public/masil.ico
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.styles.ts
  src/app/home/components/MyWalkRecord/MyWalkRecord.module.css
  src/app/layout.tsx
  src/app/user/[id]/components/MyRecordList/MyRecordList.styles.ts
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.styles.ts
Labels: refactor

#297 [Refactor] modal, loadingspinner close
  next.config.mjs
  src/app/(main)/components/AuthButton.tsx
  src/app/api/auth/[...nextauth]/options.ts
  src/app/auth/kakao/Kakao.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/Modal/Modal.tsx
Labels: refactor

#298 [Fix] auth
  src/app/api/auth/[...nextauth]/options.ts
  src/app/auth/kakao/Kakao.tsx
  src/app/signup/SignUp.controller.tsx
  src/lib/AuthLoader.tsx
  src/lib/api/User/server.ts
  src/lib/api/axios/axiosConfig.ts
  src/lib/api/serverRootAPI.ts
  src/middleware.ts
Labels: bug

#300 [Refactoring] Mate Page , API ERROR
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.ts
  src/app/log/record/utils/checkMasilError.ts
  src/app/mate/[id]/MateDetail.tsx
  src/app/mate/[id]/components/MateInfo/MateInfo.tsx
  src/app/mate/[id]/components/MateInfo/components/MateActions/MateActions.tsx
  src/app/mate/[id]/components/MateInfo/components/MateDropDownMenuWrapper/MateDropDownMenuWrapper.tsx
  src/app/mate/[id]/components/MateMembers/components/MembersList/MembersList.tsx
  src/app/mate/[id]/hooks/useCancelParticipant.ts
  src/app/mate/[id]/page.tsx
  src/app/mate/create/MateCreate.controller.tsx
  src/app/post/create/context/PostCreateContext.tsx
  src/lib/hooks/useImageUpload.ts
  src/lib/utils/checkErrorCode.ts
Labels: enhancement
