Repository Team-SilverTown/Team-SilverTown-MasilGasil-FE, pull requests merged in 2024-04, with the labels that each got.

#301 [Feat] PostView 페이지 좋아요 기능 추가
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/app/post/[id]/components/PostMemo/PostMemo.styles.ts
  src/app/post/[id]/components/PostMemo/PostMemo.tsx
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/LogDetailCard/LogDetailCard.tsx
  src/lib/api/Post/client.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/types/Response/Post.ts
Labels: enhancement

#310 [ Refactoring ] Auth 로직 개선 및 fetch 싱글톤 도입
  src/app/api/auth/[...nextauth]/options.ts
  src/app/auth/kakao/Kakao.tsx
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/user/[id]/MyPage.controller.tsx
  src/lib/AuthLoader.tsx
  src/lib/api/User/server.ts
  src/lib/api/clientRootAPI.ts
  src/lib/api/serverRootAPI.ts
  src/lib/client/apiClient.ts
  src/lib/client/axios/axiosClientInstance.ts
  src/lib/client/axios/axiosConfig.ts
  src/lib/client/axios/axiosInstance.types.ts
  src/lib/client/errors.ts
  src/lib/client/fetchAPI.ts
  src/lib/client/handleApiError.ts
  src/lib/utils/parseJwt.ts
  src/middleware.ts
Labels: bug, refactor

#315 [Fix] Auth 에러 해결
  src/app/auth/kakao/Kakao.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/lib/api/clientRootAPI.ts
  src/lib/client/fetchAPI.ts
  src/middleware.ts
Labels: bug

#313 [ Refactoring ] Tailwind
  .github/workflows/chromatic.yml
  .prettierrc
  package.json
  src/app/(main)/Main.view.tsx
  src/app/(main)/components/AuthButton.styles.ts
  src/app/(main)/components/AuthButton.tsx
  src/app/(main)/components/AuthButtonAnimation.module.css
  src/styles/GlobalStyle.tsx
  src/styles/globals.css
  src/styles/theme.ts
  tailwind.config.ts
  yarn.lock
Labels: refactor

#319 🐛fix: 리디렉션 버그 수정
  src/middleware.ts
Labels: bug

#321 [ Refacotring ] tailwind - diary
  public/sw.js
  public/swe-worker-5c72df51bb1f6ee0.js
  public/workbox-7144475a.js
  public/workbox-7144475a.js.map
  public/workbox-c06b064f.js
  src/app/diary/[id]/MasilDiary.styles.ts
  src/app/diary/[id]/MasilDiary.view.tsx
  src/app/diary/[id]/components/DiaryItem/DiaryItem.styles.ts
  src/app/diary/[id]/components/DiaryItem/DiaryItem.tsx
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.styles.ts
  src/app/diary/[id]/components/MasilDiarySheet/MasilDiarySheet.tsx
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.style.module.css
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.styles.ts
  src/app/diary/[id]/components/MonthlyStatistics/MonthlyStatistics.tsx
  src/app/diary/[id]/page.tsx
  src/components/ShadcnUi/ui/calendar.tsx
  src/components/ShadcnUi/ui/daylessCalender.tsx
  tailwind.config.ts
  yarn.lock
Labels: refactor

#323 [ Refacotring ] tailwind - home
  src/app/home/Home.styles.ts
  src/app/home/Home.view.tsx
  src/app/home/components/MyInfo/MyInfo.styles.ts
  src/app/home/components/MyInfo/MyInfo.tsx
  src/app/home/components/MyInfo/index.ts
  src/app/home/components/MyLocationWeather/MyLocationWeather.styles.ts
  src/app/home/components/MyLocationWeather/MyLocationWeather.tsx
  src/app/home/components/MyLocationWeather/utils/findDust.ts
  src/app/home/components/MyLocationWeather/utils/index.ts
  src/app/home/components/MyWalkRecord/MyWalkRecord.module.css
  src/app/home/components/MyWalkRecord/MyWalkRecord.tsx
  src/app/home/components/WalkList/components/MyLikeWalkingTrails/MyLikeWalkingTrails.style.ts
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/PopularTrailsInOurTown.styles.ts
  src/app/home/components/WalkList/components/PopularTrailsInOurTown/components/PopularWalkList.styles.ts
  src/app/home/components/WalkList/components/PopularWalkingTrails/PopularWalkingTrails.style.ts
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.styles.ts
  src/app/home/components/WalkList/components/WalkListDisplay/WalkListDisplay.tsx
  src/app/home/components/WalkStartButton/WalkStartButton.tsx
  src/app/home/components/index.ts
  tailwind.config.ts
Labels: refactor
