Repository Team-SilverTown/Team-SilverTown-MasilGasil-FE, pull requests merged in 2024-02, with the labels that each got.

#22 📝docs: Issue 양식 추가
  .github/ISSUE_TEMPLATE/🐛--버그내용-.md
  .github/ISSUE_TEMPLATE/🚀--기능요약-.md
  .github/ISSUE_TEMPLATE/🛠️--리팩토링내용-.md
Labels: documentation

#21 📝docs: PR 양식 추가
  .github/pull_request_template.md
Labels: documentation

#10 Feature/slide button/#7
  src/components/SlideButton/SlideButton.style.ts
  src/components/SlideButton/SlideButton.tsx
  src/components/SlideButton/index.ts
  src/components/index.ts
  src/stories/SlideButton.stories.tsx
  yarn.lock
Labels: enhancement

#6 Feature/button/#5
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/app/layout.tsx
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/RippleEffect/RippleEffect.module.css
  src/components/Button/RippleEffect/RippleEffect.tsx
  src/components/Button/index.ts
  src/components/LoadingDots/LoadingDots.module.css
  src/components/LoadingDots/LoadingDots.tsx
  src/components/LoadingDots/index.ts
  src/components/SlideButton/SlideButton.style.ts
  src/components/SlideButton/SlideButton.tsx
  src/components/SlideButton/index.ts
  src/components/index.ts
  src/components/uiContext/UiContext.tsx
  src/lib/hooks/useTheme.ts
  src/screens/homeScreen/Home.view.tsx
  src/stories/Button.stories.tsx
  src/stories/SlideButton.stories.tsx
  yarn.lock
Labels: enhancement

#29 [ Feat ] Masil Map 구현
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/components/MasilMap/MasilMap.style.module.css
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.styles.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
  src/components/MasilMap/components/CustomPin/CustomPin.styles.ts
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/types/OriginDataType/GeoJSON.ts
  src/types/OriginDataType/Pin.ts
Labels: enhancement

#25 [ Feat ] Log Page Layout
  .gitmessage.txt
  src/app/log/create/page.tsx
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/app/log/record/components/index.ts
  src/app/log/record/page.tsx
  src/components/MasilMap/MasilMap.style.module.css
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.styles.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
  src/components/MasilMap/components/CustomPin/CustomPin.styles.ts
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/stores/useUserLocationStore.ts
  src/types/OriginDataType/Address.ts
  src/types/OriginDataType/GeoJSON.ts
  src/types/OriginDataType/Pin.ts
  src/types/OriginDataType/index.ts
  src/types/Request/Masils.ts
  src/types/Request/index.ts
Labels: enhancement

#28 [Style] GlobalStyle 초기세팅
  .gitmessage.txt
  src/app/layout.tsx
  src/fonts/Maplestory_Light.ttf
  src/fonts/Pretendard-Black.ttf
  src/fonts/Pretendard-Bold.ttf
  src/fonts/Pretendard-ExtraBold.ttf
  src/fonts/Pretendard-ExtraLight.ttf
  src/fonts/Pretendard-Light.ttf
  src/fonts/Pretendard-Medium.ttf
  src/fonts/Pretendard-Regular.ttf
  src/fonts/Pretendard-SemiBold.ttf
  src/fonts/Pretendard-Thin.ttf
  src/styles/GlobalStyle.tsx
  src/styles/globals.css
  src/styles/theme.ts
Labels: enhancement

#23 [✨Feature] LogSimpleCard 컴포넌트 생성 /#20
  src/components/LogSimpleCard/LogSimpleCard.style.ts
  src/components/LogSimpleCard/index.tsx
Labels: enhancement

#31 Feature/input/#30
  .github/ISSUE_TEMPLATE/🐛--버그내용-.md
  .github/ISSUE_TEMPLATE/🚀--기능요약-.md
  .github/ISSUE_TEMPLATE/🛠️--리팩토링내용-.md
  .github/pull_request_template.md
  src/components/Input/Input.styles.ts
  src/components/Input/Input.tsx
  src/components/Input/index.ts
  src/components/InputLabel/InputLabel.styles.ts
  src/components/InputLabel/InputLabel.tsx
  src/components/InputLabel/index.ts
  src/components/index.ts
  src/stories/Input.stories.tsx
Labels: enhancement

#32 [Feat] LogDetailCard 컴포넌트 생성
  src/components/LogDetailCard/LogDetailCard.style.ts
  src/components/LogDetailCard/index.tsx
  src/components/icons/KebabMenu.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/stories/LogDetailCard.stories.tsx
Labels: enhancement

#48 [Refactoring] GlobalStyle 정리
  .yarnrc.yml
  public/fonts/Maplestory_Light.ttf
  public/fonts/Pretendard-Black.ttf
  public/fonts/Pretendard-Bold.ttf
  public/fonts/Pretendard-ExtraBold.ttf
  public/fonts/Pretendard-ExtraLight.ttf
  public/fonts/Pretendard-Light.ttf
  public/fonts/Pretendard-Medium.ttf
  public/fonts/Pretendard-Regular.ttf
  public/fonts/Pretendard-SemiBold.ttf
  public/fonts/Pretendard-Thin.ttf
  src/components/Button/Button.styles.ts
  src/components/Input/Input.styles.ts
  src/components/InputLabel/InputLabel.styles.ts
  src/components/LoadingDots/LoadingDots.module.css
  src/components/LogSimpleCard/LogSimpleCard.style.ts
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/components/Modal/Modal.styles.ts
  src/components/Modal/ModalLayout.tsx
  src/components/SlideButton/SlideButton.style.ts
  src/screens/homeScreen/Home.view.tsx
  src/styles/GlobalStyle.tsx
  src/styles/globals.css
  src/styles/theme.ts
  yarn.lock
Labels: enhancement

#47 [Feat] LogPage Record Step2
  src/app/layout.tsx
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.styles.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.Styles.ts
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/MasilMap/components/CustomPin/CustomPin.styles.ts
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/components/icons/MapPin.tsx
  src/components/icons/Pin.tsx
  src/components/icons/index.ts
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.styles.ts
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.tsx
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
  src/types/OriginDataType/Address.ts
Labels: enhancement

#35 [Feat] Bottom 네비게이터 구현
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/icons/Diary.tsx
  src/components/icons/DiaryFill.tsx
  src/components/icons/Exploration.tsx
  src/components/icons/ExplorationFill.tsx
  src/components/icons/Home.tsx
  src/components/icons/HomeFill.tsx
  src/components/icons/index.ts
  src/components/navigators/BottomNavigator/BottomNavigator.constants.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.style.ts
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/components/navigators/navInablePath.ts
Labels: enhancement

#42 [Feat] LogRecord STEP1 standby 구현
  src/app/layout.tsx
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.styles.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.Styles.ts
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/MasilMap/components/CustomPin/CustomPin.styles.ts
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/components/icons/MapPin.tsx
  src/components/icons/Pin.tsx
  src/components/icons/index.ts
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.styles.ts
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.tsx
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
  src/styles/theme.ts
  src/types/OriginDataType/Address.ts
Labels: enhancement

#45 [Feat] Profile 페이지 UserProfile 컴포넌트 구현
  src/app/user/[id]/components/UserInfo/UserInfo.styles.ts
  src/app/user/[id]/components/UserInfo/index.tsx
  src/app/user/[id]/components/UserWalkRecord/UserWalkRecord.styles.ts
  src/app/user/[id]/components/UserWalkRecord/index.tsx
  src/assets/userProfile.svg
Labels: enhancement

#46 [Feat] Profile 페이지 구현
  src/app/user/[id]/MyPage.view.tsx
  src/app/user/[id]/Mypage.constants.ts
  src/app/user/[id]/Mypage.controller.tsx
  src/app/user/[id]/Mypage.model.ts
  src/app/user/[id]/Mypage.styles.ts
  src/app/user/[id]/Mypage.types.ts
  src/app/user/[id]/components/MyRecordList/MyRecordList.styles.ts
  src/app/user/[id]/components/MyRecordList/index.tsx
  src/app/user/[id]/components/index.ts
  src/app/user/[id]/page.tsx
  src/components/LogDetailCard/LogDetailCard.style.ts
Labels: enhancement

#44 [Feat] SignIn Page 기초 구현
  src/app/auth/page.tsx
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.model.tsx
  src/app/signin/SignIn.styles.ts
  src/app/signin/SignIn.view.tsx
  src/app/signin/components/SignInHelper/SignInHelper.style.ts
  src/app/signin/components/SignInHelper/SignInHelper.tsx
  src/app/signin/components/SignInHelper/index.ts
  src/app/signin/components/StepButton/StepButton.tsx
  src/app/signin/components/StepButton/index.ts
  src/app/signin/components/StepLayout.tsx
  src/app/signin/components/index.ts
  src/app/signin/page.tsx
  src/app/signin/sections/SignInStep1.tsx
  src/app/signin/sections/SignInStep2.tsx
  src/app/signin/sections/SignInStep3.tsx
  src/app/signin/sections/SignInStep4.tsx
  src/app/signin/sections/index.ts
  src/components/Button/Button.styles.ts
  src/components/InputLabel/InputLabel.tsx
  src/components/navigators/navInablePath.ts
  src/styles/GlobalStyle.tsx
Labels: enhancement

#60 [Feat] LogRecord 페이지 Step3 컴포넌트 구현
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/Modal/Modal.styles.ts
  src/components/icons/EditPencil.tsx
  src/components/icons/Image.tsx
  src/components/icons/MapPin.tsx
  src/components/modalViews/PinEditModal/PinEditModal.styles.ts
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
  src/stories/Input.stories.tsx
Labels: enhancement

#52 [Feat] LogRecord Step2 Finally
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/utils/getTwoPointDistance.ts
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.tsx
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.styles.ts
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.tsx
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.styles.ts
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.tsx
  src/components/modalViews/RecordCompleteModal/CompleteRecordModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
Labels: enhancement, refactor

#51 Refactoring/position type/#50
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/utils/getTwoPointDistance.ts
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/components/Modal/Modal.styles.ts
  src/components/icons/EditPencil.tsx
  src/components/icons/Image.tsx
  src/components/icons/MapPin.tsx
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.tsx
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.styles.ts
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.tsx
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.styles.ts
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.tsx
  src/components/modalViews/PinEditModal/PinEditModal.styles.ts
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/components/modalViews/RecordCompleteModal/CompleteRecordModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
  src/stores/useUserLocationStore.ts
  src/stories/Input.stories.tsx
  src/types/OriginDataType/GeoJSON.ts
  src/types/OriginDataType/GeoPosition.ts
  src/types/OriginDataType/Pin.ts
  src/types/OriginDataType/index.ts
  src/types/Request/Masils.ts
Labels: refactor

#49 [Feat] LogRecord Step2 v2
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.styles.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.Styles.ts
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.view.tsx
  src/app/log/record/utils/getTwoPointDistance.ts
  src/components/MasilMap/MasilMap.tsx
  src/components/MasilMap/MasilMap.types.ts
  src/components/MasilMap/components/CenterMarker/CenterMarker.tsx
  src/components/MasilMap/components/CustomPin/CustomPin.tsx
  src/components/MasilMap/components/PathLine/PathLine.tsx
  src/components/Modal/Modal.styles.ts
  src/components/icons/EditPencil.tsx
  src/components/icons/Image.tsx
  src/components/icons/MapPin.tsx
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.styles.ts
  src/components/modalViews/LogInitConfirmModal/LogInitConfirmModal.tsx
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.styles.ts
  src/components/modalViews/LogRecordAlertModal/LogRecordAlertModal.tsx
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.styles.ts
  src/components/modalViews/LogRecordConfirmModal/LogRecordConfirmModal.tsx
  src/components/modalViews/PinEditModal/PinEditModal.styles.ts
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/components/modalViews/index.ts
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
  src/stores/useUserLocationStore.ts
  src/stories/Input.stories.tsx
  src/styles/theme.ts
  src/types/OriginDataType/GeoJSON.ts
  src/types/OriginDataType/GeoPosition.ts
  src/types/OriginDataType/Pin.ts
  src/types/OriginDataType/index.ts
  src/types/Request/Masils.ts
Labels: enhancement

#59 [Feat] TopNavigator 컴포넌트 구현 V1 /#4
  src/app/layout.tsx
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.view.tsx
  src/app/signin/components/SignInHelper/SignInHelper.tsx
  src/app/signin/components/StepButton/StepButton.tsx
  src/app/signin/sections/SignInStep1.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.styles.ts
  src/components/navigators/BottomNavigator/BottomNavigator.tsx
  src/components/navigators/TopNavagtor/TopNavigator.styles.ts
  src/components/navigators/TopNavagtor/TopNavigator.tsx
  src/components/navigators/TopNavagtor/components/GoBackButton.tsx
  src/components/navigators/TopNavagtor/components/StepSkipButton.tsx
  src/components/navigators/TopNavagtor/components/index.ts
  src/components/navigators/TopNavagtor/index.ts
  src/components/uiContext/UiContext.tsx
  src/components/uiContext/types/modalType.ts
  src/stores/ui/types/modalType.ts
  src/stores/ui/useModalStore.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: enhancement

#58 [Feat] Pin Detail Card 컴포넌트 구현
  src/components/PinDetailCard/PinDetailCard.styles.ts
  src/components/PinDetailCard/PinDetailCard.tsx
  src/components/PinDetailCard/index.ts
  src/components/index.ts
  src/stories/PinDetailCard.stories.tsx
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: enhancement

#63 [Feat] SignIn Step4 구현
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.model.tsx
  src/app/signin/SignIn.styles.ts
  src/app/signin/SignIn.view.tsx
  src/app/signin/sections/SignInStep4.tsx
  src/components/icons/Check.tsx
  src/components/uiContext/types/modalType.ts
  src/styles/GlobalStyle.tsx
Labels: enhancement

#64 [Feat] Auth Page 구현
  src/app/Main.controller.tsx
  src/app/Main.model.tsx
  src/app/Main.styles.ts
  src/app/Main.view.tsx
  src/app/auth/page.tsx
  src/app/page.tsx
  src/screens/homeScreen/Home.controller.tsx
  src/screens/homeScreen/Home.model.tsx
  src/screens/homeScreen/Home.styles.ts
  src/screens/homeScreen/Home.view.tsx
  src/screens/homeScreen/index.ts
  src/styles/GlobalStyle.tsx
Labels: enhancement

#66 [Feat] More List Card 컴포넌트 구현
  src/components/ListCard/ListCard.styles.ts
  src/components/ListCard/ListCard.tsx
  src/components/ListCard/index.ts
  src/components/index.ts
  src/stories/ListCard.stories.tsx
  src/utils/convertMeter.ts
  src/utils/convertSeconds.ts
Labels: enhancement

#74 [ Feat] DotIndicator 구현
  src/components/DotIndicator/DotIndicator.tsx
  src/components/DotIndicator/index.ts
  src/components/index.ts
  src/stories/DotIndicator.stories.tsx
Labels: enhancement

#72 [Feat] Tab 컴포넌트 구현
  src/components/Tab/Tab.styles.ts
  src/components/Tab/Tab.tsx
  src/components/Tab/index.ts
  src/components/index.ts
  src/stories/Tab.stories.tsx
Labels: enhancement

#77 [Faet] Loading Spinner 구현
  package.json
  src/app/layout.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/components/LoadingSpinner/LoadingSpinner.styles.ts
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/LoadingSpinner/animationData.json
  src/components/LoadingSpinner/save_transparent.json
  src/components/icons/Center.tsx
  src/components/uiContext/UiContext.tsx
  src/stores/ui/useLoadingSpinnerStore.ts
  yarn.lock
Labels: enhancement

#78 [Feat] API 핸들러 구현
  .gitignore
  next.config.mjs
  package.json
  src/app/Main.controller.tsx
  src/app/Main.model.tsx
  src/app/Main.view.tsx
  src/app/layout.tsx
  src/lib/TanstackQueryProvider.tsx
  src/lib/api/Test/serverTest.ts
  src/lib/api/Test/test.ts
  src/lib/api/axios/axiosClientInstance.ts
  src/lib/api/axios/axiosConfig.ts
  src/lib/api/axios/axiosInstance.types.ts
  src/lib/api/clientRootAPI.ts
  src/lib/api/endPoints.ts
  src/lib/api/queryKeys.ts
  src/lib/api/serverRootAPI.ts
  yarn.lock
Labels: enhancement

#90 [Hot fix] API reverse poxy 관련 수정
  next.config.mjs
  src/lib/api/clientRootAPI.ts
Labels: bug

#85 [Fix] 산책 완료 클릭시 Center 값 미적용 수정
  src/app/log/record/LogRecord.view.tsx
  src/components/MasilMap/MasilMap.style.module.css
  src/components/MasilMap/MasilMap.tsx
Labels: bug

#88 [Feat] Textarea 공용 컴포넌트 제작
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/components/Input/Input.tsx
  src/components/Textarea/Textarea.styles.ts
  src/components/Textarea/Textarea.tsx
  src/components/Textarea/index.ts
  src/components/index.ts
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/stories/Textarea.stories.tsx
Labels: enhancement

#83 [feat] StepLayout 공통 컴포넌트로 분리
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.view.tsx
  src/app/signin/components/index.ts
  src/components/StepLayout/StepLayout.tsx
  src/components/StepLayout/index.ts
  src/components/index.ts
Labels: refactor

#92 [Style] Global Style 및 Container 레이아웃 재정의
  src/app/Main.styles.ts
  src/app/Main.view.tsx
  src/app/log/record/LogRecord.styles.ts
  src/app/signin/SignIn.view.tsx
  src/app/user/[id]/MyPage.view.tsx
  src/app/user/[id]/Mypage.styles.ts
  src/app/user/[id]/components/MyRecordList/index.tsx
  src/components/icons/Diary.tsx
  src/components/icons/Exploration.tsx
  src/components/icons/ExplorationFill.tsx
  src/components/icons/Home.tsx
  src/components/navigators/BottomNavigator/BottomNavigator.styles.ts
  src/components/navigators/TopNavagtor/TopNavigator.styles.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  yarn.lock
Labels: bug

#79 [Feat] 산책 기록 완료 후 경로 그리기 및 모달
  src/app/log/record/LogRecord.constants.ts
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.controller.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.view.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/components/icons/FootPrint.tsx
  src/components/icons/RunningMan.tsx
  src/components/icons/TimeChecker.tsx
  src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.styles.ts
  src/components/modalViews/LogRecordDoneModal/LogRecordDoneModal.tsx
  src/components/modalViews/PinEditModal/PinEditModal.tsx
  src/components/uiContext/UiContext.tsx
  src/stores/ui/types/modalType.ts
  src/utils/drawPath.ts
Labels: enhancement

#98 [Hotfix] GlobalStyle 수정 (style 변경 후 레이아웃 틀어지는 부분 수정 했습니다.)
  src/app/signin/components/StepButton/StepButton.tsx
  src/styles/GlobalStyle.tsx
Labels: bug

#80 [Feat] SignIn Step2 구현
  src/app/signin/SignIn.constants.ts
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.model.tsx
  src/app/signin/SignIn.styles.ts
  src/app/signin/sections/SignInStep2.tsx
Labels: enhancement

#81 [Feat] SignIn Step3 구현
  src/app/signin/SignIn.controller.tsx
  src/app/signin/SignIn.styles.ts
  src/app/signin/sections/SignInStep3.tsx
Labels: enhancement

#97 [Feat] InputUpload 컴포넌트 구현
  src/components/InputUpload/InputUpload.constants.ts
  src/components/InputUpload/InputUpload.styles.ts
  src/components/InputUpload/InputUpload.tsx
  yarn.lock
Labels: enhancement

#95 [Feat] window UI/#87
  .gitignore
  mdx-components.tsx
  next.config.mjs
  package.json
  src/app/layout.tsx
  src/app/signin/SignIn.controller.tsx
  src/app/signin/policy/age/page.mdx
  src/app/signin/policy/layout.tsx
  src/app/signin/policy/location/page.mdx
  src/app/signin/policy/personal/page.mdx
  src/app/signin/sections/SignInStep4.tsx
  src/components/Modal/Modal.styles.ts
  src/components/Window/Window.tsx
  src/components/Window/index.ts
  src/components/index.ts
  src/components/modalViews/PinEditModal/PinEditModal.styles.ts
  src/components/navigators/navInablePath.ts
  src/components/uiContext/UiContext.tsx
  src/components/windowViews/Policy.tsx
  src/components/windowViews/index.ts
  src/stores/ui/types/windowType.ts
  src/stores/ui/useWindowStore.ts
  tailwind.config.ts
  withTwin.mjs
  yarn.lock
Labels: enhancement

#96 [Feat] LogRocord 애니메이션
  src/app/log/record/LogRecord.controller.tsx
  src/app/log/record/LogRecord.model.ts
  src/app/log/record/LogRecord.styles.ts
  src/app/log/record/LogRecord.types.ts
  src/app/log/record/LogRecord.view.tsx
  src/app/log/record/components/LogRecordEdit/LogRecordEdit.styles.ts
  src/app/log/record/components/LogRecordRecording/LogRecordRecording.controller.tsx
  src/app/log/record/components/LogRecordStandby/LogRecordStandby.controller.tsx
  src/app/user/[id]/setting/UserSetting.controller.tsx
  src/app/user/[id]/setting/UserSetting.view.tsx
  yarn.lock
Labels: enhancement

#109 [Feat] Explore layout 구현
  package.json
  src/app/explore/Explore.controller.tsx
  src/app/explore/Explore.model.tsx
  src/app/explore/Explore.styles.ts
  src/app/explore/Explore.view.tsx
  src/app/explore/page.tsx
  src/app/explore/sections/BottomSheetSection.tsx
  src/app/explore/sections/MapSection.tsx
  src/components/BottomSheet/SheetBackdrop.tsx
  src/components/BottomSheet/SheetContainer.tsx
  src/components/BottomSheet/SheetContent.tsx
  src/components/BottomSheet/SheetHeader.tsx
  src/components/BottomSheet/SheetScroller.tsx
  src/components/BottomSheet/constants.ts
  src/components/BottomSheet/context.tsx
  src/components/BottomSheet/hooks.tsx
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/sheet.tsx
  src/components/BottomSheet/styles.ts
  src/components/BottomSheet/types.tsx
  src/components/BottomSheet/use-prevent-scroll.ts
  src/components/BottomSheet/utils.ts
  src/styles/theme.ts
  yarn.lock
Labels: enhancement

#110 [Feat] User Setting Page 컴포넌트 구현
  components.json
  package.json
  src/app/user/[id]/setting/UserSetting.styles.ts
  src/app/user/[id]/setting/UserSetting.types.ts
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/SettingContent/SettingContent.styles.ts
  src/app/user/[id]/setting/components/SettingContent/SettingContent.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.view.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.view.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.view.tsx
  src/app/user/[id]/setting/components/index.ts
  src/components/ShadcnUi/ui/switch.tsx
  src/components/icons/AccountDelete.tsx
  src/components/icons/AccountManager.tsx
  src/components/icons/LogOut.tsx
  src/components/icons/NotificationActive.tsx
  src/components/icons/NotificationOff.tsx
  src/components/icons/PersonOff.tsx
  src/components/icons/PersonSearch.tsx
  src/components/icons/index.ts
  src/styles/globals.css
  src/utils/ShadcnUi.ts
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#106 [FEAT] 유저 설정 페이지 레이아웃 구현
  components.json
  package.json
  src/app/Main.view.tsx
  src/app/user/[id]/setting/UserSetting.styles.ts
  src/app/user/[id]/setting/UserSetting.types.ts
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/SettingContent/SettingContent.styles.ts
  src/app/user/[id]/setting/components/SettingContent/SettingContent.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.controller.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.view.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.controller.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.view.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.controller.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.view.tsx
  src/app/user/[id]/setting/components/index.ts
  src/app/user/[id]/setting/page.tsx
  src/components/ShadcnUi/ui/switch.tsx
  src/components/icons/AccountDelete.tsx
  src/components/icons/AccountManager.tsx
  src/components/icons/LogOut.tsx
  src/components/icons/NotificationActive.tsx
  src/components/icons/NotificationOff.tsx
  src/components/icons/PersonOff.tsx
  src/components/icons/PersonSearch.tsx
  src/components/icons/index.ts
  src/styles/GlobalStyle.tsx
  src/styles/globals.css
  src/utils/ShadcnUi.ts
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#75 [Feat] MoreList 페이지 구현 (무한 스크롤)
  components.json
  package.json
  src/app/Main.view.tsx
  src/app/layout.tsx
  src/app/more/MoreList.constants.ts
  src/app/more/MoreList.controller.tsx
  src/app/more/MoreList.model.ts
  src/app/more/MoreList.styles.ts
  src/app/more/MoreList.types.ts
  src/app/more/MoreList.view.tsx
  src/app/more/SortTab/SortTab.constants.ts
  src/app/more/SortTab/SortTab.styles.ts
  src/app/more/SortTab/SortTab.tsx
  src/app/more/SortTab/SortTab.types.ts
  src/app/more/lib/fetchMoreList.ts
  src/app/more/page.tsx
  src/app/user/[id]/Mypage.constants.ts
  src/app/user/[id]/setting/UserSetting.styles.ts
  src/app/user/[id]/setting/UserSetting.types.ts
  src/app/user/[id]/setting/UserSetting.view.tsx
  src/app/user/[id]/setting/components/SettingContent/SettingContent.styles.ts
  src/app/user/[id]/setting/components/SettingContent/SettingContent.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.controller.tsx
  src/app/user/[id]/setting/components/UserSettingAccount/UserSettingAccount.view.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.controller.tsx
  src/app/user/[id]/setting/components/UserSettingMember/UserSettingMember.view.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.controller.tsx
  src/app/user/[id]/setting/components/UserSettingOptions/UserSettingOptions.view.tsx
  src/app/user/[id]/setting/components/index.ts
  src/app/user/[id]/setting/page.tsx
  src/components/ListCard/ListCard.styles.ts
  src/components/ListCard/ListCard.tsx
  src/components/ListCard/utils/convertMeter.ts
  src/components/ListCard/utils/convertSeconds.ts
  src/components/ListCardSkeleton/ListCardSkeleton.styles.ts
  src/components/ListCardSkeleton/ListCardSkeleton.tsx
  src/components/ListCardSkeleton/index.ts
  src/components/ReactQueryProvider/index.tsx
  src/components/ShadcnUi/ui/switch.tsx
  src/components/icons/AccountDelete.tsx
  src/components/icons/AccountManager.tsx
  src/components/icons/LogOut.tsx
  src/components/icons/NotificationActive.tsx
  src/components/icons/NotificationOff.tsx
  src/components/icons/PersonOff.tsx
  src/components/icons/PersonSearch.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/lib/TanstackQueryProvider.tsx
  src/styles/GlobalStyle.tsx
  src/styles/globals.css
  src/utils/ShadcnUi.ts
  src/utils/drawPath.ts
  tailwind.config.ts
  yarn.lock
Labels: enhancement

#124 [Feat] MoreList 페이지 구현 (무한 스크롤)
  package.json
  src/app/layout.tsx
  src/app/more/MoreList.constants.ts
  src/app/more/MoreList.controller.tsx
  src/app/more/MoreList.model.ts
  src/app/more/MoreList.styles.ts
  src/app/more/MoreList.types.ts
  src/app/more/MoreList.view.tsx
  src/app/more/SortTab/SortTab.constants.ts
  src/app/more/SortTab/SortTab.styles.ts
  src/app/more/SortTab/SortTab.tsx
  src/app/more/SortTab/SortTab.types.ts
  src/app/more/lib/fetchMoreList.ts
  src/app/more/page.tsx
  src/app/user/[id]/Mypage.constants.ts
  src/components/ListCard/ListCard.styles.ts
  src/components/ListCard/ListCard.tsx
  src/components/ListCardSkeleton/ListCardSkeleton.styles.ts
  src/components/ListCardSkeleton/ListCardSkeleton.tsx
  src/components/ListCardSkeleton/index.ts
  src/components/ReactQueryProvider/index.tsx
  src/components/index.ts
  src/lib/TanstackQueryProvider.tsx
  src/utils/convertMeter.ts
  src/utils/drawPath.ts
  yarn.lock
Labels: enhancement

#125 [Feat] Avatar 컴포넌트 구현
  src/components/Avatar/Avatar.styles.ts
  src/components/Avatar/Avatar.tsx
Labels: enhancement
